language: node_js
node_js:
  - "11.5.0"
addons:
    code_climate:
        repo_token: 8ae87d7c92c6908ec71e9d02f93932b85660843c9e186837aca649c7a75d2e00
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
